In [1]:
import pandas as pd

In [2]:
from nba_api.stats.endpoints import teamgamelogs
team = teamgamelogs.TeamGameLogs(season_nullable='2001-02', game_segment_nullable='First Half')
a= team.get_data_frames()[0]

In [3]:
df = pd.DataFrame(a)

In [4]:
df

,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,2001-02,1610612765,DET,Detroit Pistons,0020101181,2002-04-17T00:00:00,DET vs. MIL,W,24.0,25,...,172,168,1336,494,1673,707,903,80,50,50
1,2001-02,1610612749,MIL,Milwaukee Bucks,0020101181,2002-04-17T00:00:00,MIL @ DET,L,24.0,19,...,2077,1963,986,856,1101,218,1555,80,1580,2320
2,2001-02,1610612758,SAC,Sacramento Kings,0020101188,2002-04-17T00:00:00,SAC @ LAL,L,24.0,20,...,525,2144,1336,2146,1101,218,140,80,462,1318
3,2001-02,1610612752,NYK,New York Knicks,0020101179,2002-04-17T00:00:00,NYK vs. NJN,L,24.0,18,...,271,1753,1336,1771,1673,1,1555,1,1723,790
4,2001-02,1610612737,ATL,Atlanta Hawks,0020101176,2002-04-17T00:00:00,ATL @ BOS,L,24.0,13,...,172,1963,1336,41,1101,1743,19,80,2076,1943
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2373,2001-02,1610612762,UTA,Utah Jazz,0020100009,2001-10-30T00:00:00,UTA vs. MIL,L,24.0,21,...,1757,55,1915,113,637,1,903,80,462,894
2374,2001-02,1610612759,SAS,San Antonio Spurs,0020100008,2001-10-30T00:00:00,SAS vs. LAC,W,24.0,17,...,525,1166,1652,1287,1673,1,2275,80,1068,790
2375,2001-02,1610612754,IND,Indiana Pacers,0020100003,2001-10-30T00:00:00,IND @ NJN,L,24.0,23,...,525,648,1915,1287,1101,1743,903,80,554,501
2376,2001-02,1610612764,WAS,Washington Wizards,0020100002,2001-10-30T00:00:00,WAS @ NYK,L,24.0,19,...,1757,648,171,244,317,218,1839,80,1723,972
2377,2001-02,1610612752,NYK,New York Knicks,0020100002,2001-10-30T00:00:00,NYK vs. WAS,W,24.0,15,...,172,1963,1915,2328,1673,1743,903,80,1921,1318

In [5]:
year = '2001-02'
team = teamgamelogs.TeamGameLogs(season_nullable=year, game_segment_nullable='First Half')
b= team.get_data_frames()[0]

In [6]:
type(b)

pandas.core.frame.DataFrame

In [7]:
b

,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,2001-02,1610612765,DET,Detroit Pistons,0020101181,2002-04-17T00:00:00,DET vs. MIL,W,24.0,25,...,172,168,1336,494,1673,707,903,80,50,50
1,2001-02,1610612749,MIL,Milwaukee Bucks,0020101181,2002-04-17T00:00:00,MIL @ DET,L,24.0,19,...,2077,1963,986,856,1101,218,1555,80,1580,2320
2,2001-02,1610612758,SAC,Sacramento Kings,0020101188,2002-04-17T00:00:00,SAC @ LAL,L,24.0,20,...,525,2144,1336,2146,1101,218,140,80,462,1318
3,2001-02,1610612752,NYK,New York Knicks,0020101179,2002-04-17T00:00:00,NYK vs. NJN,L,24.0,18,...,271,1753,1336,1771,1673,1,1555,1,1723,790
4,2001-02,1610612737,ATL,Atlanta Hawks,0020101176,2002-04-17T00:00:00,ATL @ BOS,L,24.0,13,...,172,1963,1336,41,1101,1743,19,80,2076,1943
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2373,2001-02,1610612762,UTA,Utah Jazz,0020100009,2001-10-30T00:00:00,UTA vs. MIL,L,24.0,21,...,1757,55,1915,113,637,1,903,80,462,894
2374,2001-02,1610612759,SAS,San Antonio Spurs,0020100008,2001-10-30T00:00:00,SAS vs. LAC,W,24.0,17,...,525,1166,1652,1287,1673,1,2275,80,1068,790
2375,2001-02,1610612754,IND,Indiana Pacers,0020100003,2001-10-30T00:00:00,IND @ NJN,L,24.0,23,...,525,648,1915,1287,1101,1743,903,80,554,501
2376,2001-02,1610612764,WAS,Washington Wizards,0020100002,2001-10-30T00:00:00,WAS @ NYK,L,24.0,19,...,1757,648,171,244,317,218,1839,80,1723,972
2377,2001-02,1610612752,NYK,New York Knicks,0020100002,2001-10-30T00:00:00,NYK vs. WAS,W,24.0,15,...,172,1963,1915,2328,1673,1743,903,80,1921,1318

In [8]:
df_b = pd.DataFrame(b)

In [9]:
df_b

,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,2001-02,1610612765,DET,Detroit Pistons,0020101181,2002-04-17T00:00:00,DET vs. MIL,W,24.0,25,...,172,168,1336,494,1673,707,903,80,50,50
1,2001-02,1610612749,MIL,Milwaukee Bucks,0020101181,2002-04-17T00:00:00,MIL @ DET,L,24.0,19,...,2077,1963,986,856,1101,218,1555,80,1580,2320
2,2001-02,1610612758,SAC,Sacramento Kings,0020101188,2002-04-17T00:00:00,SAC @ LAL,L,24.0,20,...,525,2144,1336,2146,1101,218,140,80,462,1318
3,2001-02,1610612752,NYK,New York Knicks,0020101179,2002-04-17T00:00:00,NYK vs. NJN,L,24.0,18,...,271,1753,1336,1771,1673,1,1555,1,1723,790
4,2001-02,1610612737,ATL,Atlanta Hawks,0020101176,2002-04-17T00:00:00,ATL @ BOS,L,24.0,13,...,172,1963,1336,41,1101,1743,19,80,2076,1943
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2373,2001-02,1610612762,UTA,Utah Jazz,0020100009,2001-10-30T00:00:00,UTA vs. MIL,L,24.0,21,...,1757,55,1915,113,637,1,903,80,462,894
2374,2001-02,1610612759,SAS,San Antonio Spurs,0020100008,2001-10-30T00:00:00,SAS vs. LAC,W,24.0,17,...,525,1166,1652,1287,1673,1,2275,80,1068,790
2375,2001-02,1610612754,IND,Indiana Pacers,0020100003,2001-10-30T00:00:00,IND @ NJN,L,24.0,23,...,525,648,1915,1287,1101,1743,903,80,554,501
2376,2001-02,1610612764,WAS,Washington Wizards,0020100002,2001-10-30T00:00:00,WAS @ NYK,L,24.0,19,...,1757,648,171,244,317,218,1839,80,1723,972
2377,2001-02,1610612752,NYK,New York Knicks,0020100002,2001-10-30T00:00:00,NYK vs. WAS,W,24.0,15,...,172,1963,1915,2328,1673,1743,903,80,1921,1318

In [10]:
def teamdatabyseason(year1,year2):
    year_first = year1
    year_last = year2
    all_seasons = []
    for y in season_years:
        team = teamgamelogs.TeamGameLogs(season_nullable=season_loop, game_segment_nullable='First Half')
        team = team.get_data_frames()[0]
        all_seasons.append(team)
    return all_seasons

'2000-01'

In [11]:
start_season = '1986-87'
list1=start_season.split('-')

In [12]:
first_part=int(list1[0])+1

In [13]:
first_part

1987

In [14]:
second_part=int(list1[1])+1

In [15]:
type(second_part)

int

In [16]:
season_loop='-'.join([str(first_part), str(second_part)])

In [ ]:
start_season = '2000-01'
seasons_all_list=[]
for i in range(20):
    list1=start_season.split('-')
    first_part=int(list1[0])+1
    second_part=int(list1[0])+2
    second_part=str(second_part)[2:]
    season_years='-'.join([str(first_part), str(second_part)])
    start_season=season_years
    team = teamgamelogs.TeamGameLogs(season_nullable=season_years, game_segment_nullable='First Half')
    team = team.get_data_frames()[0]
    seasons_all_list.append(team)

In [ ]:
all_seasons_df = pd.concat(seasons_all_list, ignore_index=True)

In [ ]:
all_seasons_df.to_csv('all_seasons_df.csv', index=False)

In [ ]:
type(season_years)

In [ ]:
a=4
str(a)
type(a)

In [ ]:
teamdatabyseason(2016,2019)

In [ ]:
team00_01 = teamgamelogs.TeamGameLogs(season_nullable='2000-01', game_segment_nullable='First Half')
team00_01 = team00_01.get_data_frames()[0]

In [ ]:
team00_01

In [ ]:
from nba_api.stats.endpoints import teamgamelogs

team01_02 = teamgamelogs.TeamGameLogs(season_nullable='2001-02', game_segment_nullable='First Half')
team01_02 = team01_02.get_data_frames()[0]

In [ ]:
team01_02

In [ ]:
result = team00_01.append(team01_02, ignore_index=True)

In [ ]:
result

In [ ]:
team00_01 = teamgamelogs.TeamGameLogs(season_nullable='2000-01', game_segment_nullable='First Half')
team00_01 = team00_01.get_data_frames()[0]

team01_02 = teamgamelogs.TeamGameLogs(season_nullable='2001-02', game_segment_nullable='First Half')
team01_02 = team01_02.get_data_frames()[0]

team02_03 = teamgamelogs.TeamGameLogs(season_nullable='2002-03', game_segment_nullable='First Half')
team02_03 = team02_03.get_data_frames()[0]

team03_04 = teamgamelogs.TeamGameLogs(season_nullable='2003-04', game_segment_nullable='First Half')
team03_04 = team03_04.get_data_frames()[0]

team04_05 = teamgamelogs.TeamGameLogs(season_nullable='2004-05', game_segment_nullable='First Half')
team04_05 = team04_05.get_data_frames()[0]

team05_06 = teamgamelogs.TeamGameLogs(season_nullable='2005-06', game_segment_nullable='First Half')
team05_06 = team05_06.get_data_frames()[0]

team06_07 = teamgamelogs.TeamGameLogs(season_nullable='2006-07', game_segment_nullable='First Half')
team06_07 = team06_07.get_data_frames()[0]

team07_08 = teamgamelogs.TeamGameLogs(season_nullable='2007-08', game_segment_nullable='First Half')
team07_08 = team07_08.get_data_frames()[0]

team08_09 = teamgamelogs.TeamGameLogs(season_nullable='2008-09', game_segment_nullable='First Half')
team08_09 = team08_09.get_data_frames()[0]

team09_10 = teamgamelogs.TeamGameLogs(season_nullable='2009-10', game_segment_nullable='First Half')
team09_10 = team09_10.get_data_frames()[0]

team10_11 = teamgamelogs.TeamGameLogs(season_nullable='2010-11', game_segment_nullable='First Half')
team10_11 = team10_11.get_data_frames()[0]

team11_12 = teamgamelogs.TeamGameLogs(season_nullable='2011-12', game_segment_nullable='First Half')
team11_12 = team11_12.get_data_frames()[0]

team12_13 = teamgamelogs.TeamGameLogs(season_nullable='2012-13', game_segment_nullable='First Half')
team12_13 = team12_13.get_data_frames()[0]

team13_14 = teamgamelogs.TeamGameLogs(season_nullable='2013-14', game_segment_nullable='First Half')
team13_14 = team13_14.get_data_frames()[0]

team14_15 = teamgamelogs.TeamGameLogs(season_nullable='2014-15', game_segment_nullable='First Half')
team14_15 = team14_15.get_data_frames()[0]

team15_16 = teamgamelogs.TeamGameLogs(season_nullable='2015-16', game_segment_nullable='First Half')
team15_16 = team15_16.get_data_frames()[0]

team16_17 = teamgamelogs.TeamGameLogs(season_nullable='2016-17', game_segment_nullable='First Half')
team16_17 = team16_17.get_data_frames()[0]

team17_18 = teamgamelogs.TeamGameLogs(season_nullable='2017-18', game_segment_nullable='First Half')
team17_18 = team17_18.get_data_frames()[0]

team18_19 = teamgamelogs.TeamGameLogs(season_nullable='2018-19', game_segment_nullable='First Half')
team18_19 = team18_19.get_data_frames()[0]

team19_20 = teamgamelogs.TeamGameLogs(season_nullable='2019-20', game_segment_nullable='First Half')
team19_20 = team19_20.get_data_frames()[0]

In [ ]:
seasons_00_20_df = pd.concat([team00_01, team01_02, team02_03, team03_04, team04_05,
                        team05_06, team06_07, team07_08, team08_09, team09_10,
                        team10_11, team11_12, team12_13, team13_14, team14_15,
                        team15_16, team16_17, team17_18, team18_19, team19_20],
                        ignore_index=True)

In [ ]:
seasons_00_20_df