In [4]:
from nba_api.stats.static import teams

nba_teams = teams.get_teams()
# Select the dictionary for the Celtics, which contains their team ID
celtics = [team for team in nba_teams if team['abbreviation'] == 'BOS'][0]
celtics_id = celtics['id']

In [5]:
from nba_api.stats.endpoints import leaguegamefinder

# Query for games where the Celtics were playing
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=celtics_id)
# The first DataFrame of those returned is what we want.
games = gamefinder.get_data_frames()[0]
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22020,1610612738,BOS,Boston Celtics,0022000280,2021-01-27,BOS @ SAS,L,239,106,...,0.857,13,26,39,15,10,4,10,14,-4.0
1,22020,1610612738,BOS,Boston Celtics,0022000262,2021-01-25,BOS @ CHI,W,239,119,...,0.800,6,38,44,28,9,6,12,18,16.0
2,22020,1610612738,BOS,Boston Celtics,0022000250,2021-01-24,BOS vs. CLE,W,239,141,...,0.852,13,42,55,26,14,8,15,23,38.0
3,22020,1610612738,BOS,Boston Celtics,0022000233,2021-01-22,BOS @ PHI,L,239,110,...,0.800,10,22,32,23,10,5,11,21,-12.0
4,22020,1610612738,BOS,Boston Celtics,0022000218,2021-01-20,BOS @ PHI,L,240,109,...,0.650,10,35,45,22,3,0,16,29,-8.0

In [6]:
# Subset the games to when the last 4 digits of SEASON_ID were 2017.
games_1718 = games[games.SEASON_ID.str[-4:] == '2000']
games_1718.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
1931,22000,1610612738,BOS,Boston Celtics,0020001179,2001-04-18,BOS vs. CHH,L,240,92,...,0.840,11,31,42,18,10,6,13,22,-5.0
1932,22000,1610612738,BOS,Boston Celtics,0020001154,2001-04-15,BOS vs. NJN,W,241,95,...,0.688,14,36,50,26,8,3,16,17,7.0
1933,22000,1610612738,BOS,Boston Celtics,0020001142,2001-04-13,BOS @ IND,L,265,108,...,0.737,13,32,45,24,12,3,24,28,-5.0
1934,22000,1610612738,BOS,Boston Celtics,0020001125,2001-04-11,BOS vs. MIA,L,239,97,...,0.867,9,22,31,14,4,5,9,22,-5.0
1935,22000,1610612738,BOS,Boston Celtics,0020001112,2001-04-09,BOS @ PHI,L,240,95,...,0.692,10,20,30,23,5,4,12,24,-13.0

In [7]:
from nba_api.stats.endpoints import playbyplayv2
pbp = playbyplayv2.PlayByPlayV2('0020001179')
pbp = pbp.get_data_frames()[0]
pbp.head(20)

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,...,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG
0,0020001179,0,12,0,1,11:12 AM,12:00,None,None,None,...,None,None,0,0,None,NaN,None,None,None,0
1,0020001179,1,10,0,1,11:12 AM,12:00,Jump Ball Blount vs. Campbell: Tip to Williams,None,None,...,Hornets,CHH,4,677,Eric Williams,1.610613e+09,Boston,Celtics,BOS,0
2,0020001179,2,6,2,1,11:13 AM,11:48,None,None,Davis S.FOUL (P1.T1),...,None,None,1,0,None,NaN,None,None,None,0
3,0020001179,3,3,11,1,11:13 AM,11:48,Pierce Free Throw 1 of 2 (1 PTS),None,None,...,None,None,0,0,None,NaN,None,None,None,0
4,0020001179,4,3,12,1,11:13 AM,11:48,Pierce Free Throw 2 of 2 (2 PTS),None,None,...,None,None,0,0,None,NaN,None,None,None,0
5,0020001179,5,1,1,1,11:14 AM,11:25,None,None,Mashburn 25' 3PT Jump Shot (3 PTS) (Davis 1 AST),...,Hornets,CHH,0,0,None,NaN,None,None,None,0
6,0020001179,6,1,1,1,11:14 AM,11:09,Pierce 16' Jump Shot (4 PTS) (Blount 1 AST),None,None,...,Celtics,BOS,0,0,None,NaN,None,None,None,0
7,0020001179,7,1,1,1,11:14 AM,11:01,None,None,Davis 9' Jump Shot (2 PTS),...,None,None,0,0,None,NaN,None,None,None,0
8,0020001179,8,1,1,1,11:15 AM,10:51,Pierce 25' 3PT Jump Shot (7 PTS) (Williams 1 AST),None,None,...,Celtics,BOS,0,0,None,NaN,None,None,None,0
9,0020001179,9,2,1,1,11:15 AM,10:38,None,None,MISS Mashburn 14' Jump Shot,...,None,None,0,0,None,NaN,None,None,None,0
10,0020001179,10,4,0,1,11:15 AM,10:36,Blount REBOUND (Off:0 Def:1),None,None,...,None,None,0,0,None,NaN,None,None,None,0
11,0020001179,11,5,1,1,11:15 AM,10:31,Walker Bad Pass Turnover (P1.T1),None,None,...,None,None,0,0,None,NaN,None,None,None,0
12,0020001179,12,1,1,1,11:15 AM,10:17,None,None,Campbell 9' Jump Shot (2 PTS) (Mashburn 1 AST),...,Hornets,CHH,0,0,None,NaN,None,None,None,0
13,0020001179,13,2,1,1,11:16 AM,9:58,MISS Pierce 14' Jump Shot,None,None,...,None,None,0,0,None,NaN,None,None,None,0
14,0020001179,14,4,0,1,11:16 AM,9:56,None,None,Mashburn REBOUND (Off:0 Def:1),...,None,None,0,0,None,NaN,None,None,None,0
15,0020001179,15,2,1,1,11:16 AM,9:48,None,None,MISS Wesley 16' Jump Shot,...,None,None,0,0,None,NaN,None,None,None,0
16,0020001179,16,4,0,1,11:16 AM,9:46,Pierce REBOUND (Off:0 Def:1),None,None,...,None,None,0,0,None,NaN,None,None,None,0
17,0020001179,17,2,1,1,11:16 AM,9:28,MISS McCarty 18' Jump Shot,None,None,...,None,None,0,0,None,NaN,None,None,None,0
18,0020001179,18,4,0,1,11:16 AM,9:28,None,None,Hornets Rebound,...,None,None,0,0,None,NaN,None,None,None,0
19,0020001179,19,6,3,1,11:16 AM,9:28,Blount L.B.FOUL (P1.T1),None,None,...,None,None,1,0,None,NaN,None,None,None,0

In [8]:
type(pbp)

pandas.core.frame.DataFrame

In [9]:
pbp.shape

(463, 34)

In [10]:
from sqlalchemy import create_engine
import pandas as pd

In [11]:
nba_1 = games_1718

In [12]:
engine = create_engine('postgresql://johnmetzger:localhost@localhost:5432/nba_1')

In [14]:
nba_1.to_sql('nba_1',engine,index=False)

In [15]:
query = 'SELECT * FROM nba_1;'
df = pd.read_sql(query, engine)

df.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22000,1610612738,BOS,Boston Celtics,0020001179,2001-04-18,BOS vs. CHH,L,240,92,...,0.840,11,31,42,18,10,6,13,22,-5.0
1,22000,1610612738,BOS,Boston Celtics,0020001154,2001-04-15,BOS vs. NJN,W,241,95,...,0.688,14,36,50,26,8,3,16,17,7.0
2,22000,1610612738,BOS,Boston Celtics,0020001142,2001-04-13,BOS @ IND,L,265,108,...,0.737,13,32,45,24,12,3,24,28,-5.0
3,22000,1610612738,BOS,Boston Celtics,0020001125,2001-04-11,BOS vs. MIA,L,239,97,...,0.867,9,22,31,14,4,5,9,22,-5.0
4,22000,1610612738,BOS,Boston Celtics,0020001112,2001-04-09,BOS @ PHI,L,240,95,...,0.692,10,20,30,23,5,4,12,24,-13.0

In [21]:
from nba_py import team

In [9]:
from nba_api.stats.endpoints import teamdashboardbygeneralsplits
# Anthony Davis
career = teamdashboardbygeneralsplits.TeamDashboardByGeneralSplits(team_id='1610612738')
career.get_data_frames()[1]

,GROUP_SET,GROUP_VALUE,TEAM_GAME_LOCATION,GP,W,L,W_PCT,MIN,FGM,FGA,...,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,CFID,CFPARAMS
0,Location,Home,Home,8,5,3,0.625,384.0,337,723,...,1,1,2,1,1,2,2,1,153,Home
1,Location,Road,Road,10,5,5,0.500,480.0,420,876,...,2,2,1,2,2,1,1,2,153,Road

In [38]:
career

In [39]:
career.game_segment

AttributeError: 'TeamDashboardByGeneralSplits' object has no attribute 'game_segment'

In [4]:
import pandas as pd
import numpy as np

In [19]:
pd.set_option('max_columns', None)

In [69]:
from nba_api.stats.endpoints import teamgamelogs
# Anthony Davis
team = teamgamelogs.TeamGameLogs(game_segment_nullable='First Half', date_from_nullable='2000-2001', date_to_nullable='2001-2002')
a= team.get_data_frames()[1]

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [62]:
df = pd.DataFrame(a)

In [52]:
len(df.TEAM_ID.unique())

29

In [65]:
get_date_format()

NameError: name 'get_date_format' is not defined

In [59]:
df

Empty DataFrame
Columns: [SEASON_YEAR, TEAM_ID, TEAM_ABBREVIATION, TEAM_NAME, GAME_ID, GAME_DATE, MATCHUP, WL, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, TOV, STL, BLK, BLKA, PF, PFD, PTS, PLUS_MINUS, GP_RANK, W_RANK, L_RANK, W_PCT_RANK, MIN_RANK, FGM_RANK, FGA_RANK, FG_PCT_RANK, FG3M_RANK, FG3A_RANK, FG3_PCT_RANK, FTM_RANK, FTA_RANK, FT_PCT_RANK, OREB_RANK, DREB_RANK, REB_RANK, AST_RANK, TOV_RANK, STL_RANK, BLK_RANK, BLKA_RANK, PF_RANK, PFD_RANK, PTS_RANK, PLUS_MINUS_RANK]
Index: []