# Imports

In [1]:
import pandas as pd
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')
%matplotlib inline
np.set_printoptions(suppress=True)

Goal:

In [2]:
pd.set_option('display.max_columns', None)

In [5]:
# Note that "all_seasons_df" is already sliced and diced while
# "all_seasons_df.csv" is raw and the one to go into PostGres.

all_seasons_df = pd.read_csv('/Users/johnmetzger/Desktop/Coding/Projects/Project3/all_seasons_df.csv')

In [6]:
all_seasons_df

,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,2001-02,1610612765,DET,Detroit Pistons,20101181,2002-04-17T00:00:00,DET vs. MIL,W,24.0,25,46,0.543,8,12,0.667,6,7,0.857,9,18,27,16,8.0,5,1,2,9,0,64,20.0,1,1,1,1,1,71,327,283,8,119,129,1384,1662,529,259,403,172,168,1336,494,1673,707,903,80,50,50
1,2001-02,1610612749,MIL,Milwaukee Bucks,20101181,2002-04-17T00:00:00,MIL @ DET,L,24.0,19,40,0.475,2,6,0.333,4,8,0.500,5,11,16,8,7.0,4,2,1,11,0,44,-20.0,1,1190,1190,1190,1,987,1391,929,995,1160,1136,1903,1445,2170,1322,2044,2077,1963,986,856,1101,218,1555,80,1580,2320
2,2001-02,1610612758,SAC,Sacramento Kings,20101188,2002-04-17T00:00:00,SAC @ LAL,L,24.0,20,39,0.513,2,5,0.400,12,17,0.706,3,21,24,7,8.0,1,2,1,6,0,54,-2.0,1,1190,1190,1190,1,690,1636,515,995,1454,907,259,177,1514,1973,86,525,2144,1336,2146,1101,218,140,80,462,1318
3,2001-02,1610612752,NYK,New York Knicks,20101179,2002-04-17T00:00:00,NYK vs. NJN,L,24.0,18,45,0.400,3,14,0.214,4,4,1.000,9,17,26,9,8.0,2,1,0,11,1,43,4.0,1,1190,1190,1190,1,1280,450,1774,566,42,1781,1903,2153,1,259,602,271,1753,1336,1771,1673,1,1555,1,1723,790
4,2001-02,1610612737,ATL,Atlanta Hawks,20101176,2002-04-17T00:00:00,ATL @ BOS,L,24.0,13,43,0.302,0,3,0.000,13,16,0.813,10,17,27,8,8.0,8,2,4,4,0,39,-10.0,1,1190,1190,1190,1,2267,785,2341,2083,2001,2083,174,243,853,145,602,172,1963,1336,41,1101,1743,19,80,2076,1943
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46273,2020-21,1610612743,DEN,Denver Nuggets,22000019,2020-12-23T00:00:00,DEN vs. SAC,L,24.0,23,45,0.511,5,12,0.417,9,10,0.900,7,21,28,13,8.0,2,4,4,10,11,60,7.0,1,305,305,305,1,140,267,168,372,541,213,198,252,123,82,100,58,241,347,434,69,459,348,108,182,158
46274,2020-21,1610612751,BKN,Brooklyn Nets,22000001,2020-12-22T00:00:00,BKN vs. GSW,W,24.0,23,47,0.489,9,20,0.450,8,9,0.889,4,24,28,11,13.0,5,6,2,10,10,63,18.0,1,1,1,1,1,140,156,219,91,139,156,245,307,137,309,24,58,382,593,134,15,170,348,191,124,44
46275,2020-21,1610612747,LAL,Los Angeles Lakers,22000002,2020-12-22T00:00:00,LAL vs. LAC,L,24.0,17,40,0.425,5,17,0.294,15,20,0.750,3,21,24,10,11.0,3,0,0,12,17,54,-2.0,1,305,305,305,1,512,536,417,372,313,446,23,15,335,427,100,199,459,540,324,564,1,502,3,355,336
46276,2020-21,1610612744,GSW,Golden State Warriors,22000001,2020-12-22T00:00:00,GSW @ BKN,L,24.0,17,53,0.321,4,17,0.235,7,10,0.700,6,17,23,10,9.0,4,2,6,10,10,45,-18.0,1,305,305,305,1,512,14,592,466,313,522,300,252,416,136,311,249,459,420,223,267,584,348,191,541,562
46277,2020-21,1610612746,LAC,LA Clippers,22000002,2020-12-22T00:00:00,LAC @ LAL,W,24.0,21,45,0.467,7,21,0.333,7,9,0.778,3,18,21,12,12.0,7,0,0,17,12,56,2.0,1,1,1,1,1,260,267,285,211,94,352,300,307,298,427,254,366,322,573,33,564,1,605,68,293,250

In [30]:
engine = create_engine('postgresql://johnmetzger:localhost@localhost:5432/nba_ht')

nba_all_data = pd.read_csv('/Users/johnmetzger/Desktop/Coding/Projects/Project3/all_seasons_df.csv')

# I'm choosing to name this table "nba_all_data" for "NBA Halftime"
nba_ht.to_sql('nba_all_data', engine, index=True)

GET Data on a team

In [66]:
#Here, 'DET' is used as an example
# This uses the WHERE Command

Team ='''
SELECT * FROM nba_all_data WHERE "TEAM_ABBREVIATION"='DET';
    '''
    
tanks = pd.read_sql(Team, engine)

tanks

,index,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,0,2001-02,1610612765,DET,Detroit Pistons,20101181,2002-04-17T00:00:00,DET vs. MIL,W,24.0,25,46,0.543,8,12,0.667,6,7,0.857,9,18,27,16,8.0,5,1,2,9,0,64,20.0,1,1,1,1,1,71,327,283,8,119,129,1384,1662,529,259,403,172,168,1336,494,1673,707,903,80,50,50
1,33,2001-02,1610612765,DET,Detroit Pistons,20101167,2002-04-16T00:00:00,DET @ NJN,W,24.0,14,37,0.378,3,11,0.273,15,19,0.789,5,19,24,9,8.0,1,7,4,8,0,46,1.0,1,1,1,1,1,2164,1955,1996,566,177,1530,76,84,1006,1322,263,525,1753,1336,2146,27,1743,563,80,1334,1062
2,74,2001-02,1610612765,DET,Detroit Pistons,20101150,2002-04-13T00:00:00,DET @ CHI,W,24.0,27,48,0.563,3,9,0.333,6,7,0.857,3,12,15,19,2.0,7,1,4,10,0,63,11.0,1,1,1,1,1,20,149,189,566,435,1136,1384,1662,529,1973,1862,2170,29,16,113,1673,1743,1220,80,65,317
3,100,2001-02,1610612765,DET,Detroit Pistons,20101142,2002-04-12T00:00:00,DET vs. SAS,L,24.0,21,36,0.583,3,6,0.500,6,9,0.667,2,15,17,16,9.0,5,2,4,7,0,51,3.0,1,1190,1190,1190,1,500,2098,119,566,1160,452,1384,1251,1644,2186,1106,1930,168,1652,494,1101,1743,308,80,726,894
4,131,2001-02,1610612765,DET,Detroit Pistons,20101127,2002-04-10T00:00:00,DET vs. CHI,L,24.0,20,38,0.526,6,10,0.600,5,6,0.833,2,17,19,14,10.0,5,3,3,7,0,51,6.0,1,1190,1190,1190,1,690,1803,416,54,297,264,1671,1842,668,2186,602,1548,452,1915,494,637,1279,308,80,726,639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1542,46139,2020-21,1610612765,DET,Detroit Pistons,22000070,2021-01-01T00:00:00,DET vs. BOS,W,24.0,23,43,0.535,5,15,0.333,4,7,0.571,4,19,23,11,11.0,5,2,4,8,9,55,15.0,1,1,1,1,1,140,388,106,372,413,352,473,417,536,309,190,249,382,540,134,267,459,161,262,329,61
1543,46174,2020-21,1610612765,DET,Detroit Pistons,22000047,2020-12-29T00:00:00,DET vs. GSW,L,24.0,15,50,0.300,8,24,0.333,13,15,0.867,12,19,31,8,5.0,3,1,2,11,14,51,3.0,1,305,305,305,1,576,50,601,149,43,352,55,79,170,4,190,9,559,100,324,440,170,419,14,426,228
1544,46197,2020-21,1610612765,DET,Detroit Pistons,22000041,2020-12-28T00:00:00,DET @ ATL,L,24.0,20,48,0.417,6,19,0.316,10,13,0.769,7,13,20,11,3.0,4,1,3,10,9,56,-9.0,1,305,305,305,1,326,117,446,286,193,403,132,135,318,82,530,412,382,25,223,440,343,348,262,293,465
1545,46237,2020-21,1610612765,DET,Detroit Pistons,22000023,2020-12-26T00:00:00,DET vs. CLE,L,24.0,17,44,0.386,9,20,0.450,10,15,0.667,3,21,24,12,8.0,2,1,2,8,8,53,-6.0,1,305,305,305,1,512,331,529,91,139,156,132,79,435,427,100,199,322,347,434,440,170,161,357,381,419
1546,46265,2020-21,1610612765,DET,Detroit Pistons,22000018,2020-12-23T00:00:00,DET @ MIN,L,24.0,25,49,0.510,5,18,0.278,2,4,0.500,4,19,23,17,5.0,1,1,1,11,9,57,1.0,1,305,305,305,1,57,79,179,372,255,467,569,551,562,309,190,249,51,100,533,440,46,419,262,269,274

In [82]:
#Here, 'DET' is used as an example
# Pick attribtues to order.  Here you are selecting from the df=nba_all_data
# and finding out what values in columns (after first SELECT)
# are greater than the average of a variable.  Here it was 'FG_PCT'

Winning ='''
    WITH temporaryTable(averageValue) as (SELECT avg("FG_PCT")
    from nba_all_data)
    SELECT "SEASON_YEAR","TEAM_NAME", "FG_PCT" 
    FROM nba_all_data, temporaryTable 
    WHERE nba_all_data."FG_PCT" > temporaryTable.averageValue;
        '''

Team_winning = pd.read_sql(Winning, engine)

Team_winning

      SEASON_YEAR              TEAM_NAME  FG_PCT
0         2001-02        Detroit Pistons   0.543
1         2001-02        Milwaukee Bucks   0.475
2         2001-02       Sacramento Kings   0.513
3         2001-02      San Antonio Spurs   0.472
4         2001-02  Golden State Warriors   0.556
...           ...                    ...     ...
22952     2020-21             Miami Heat   0.538
22953     2020-21        Toronto Raptors   0.467
22954     2020-21         Denver Nuggets   0.511
22955     2020-21          Brooklyn Nets   0.489
22956     2020-21            LA Clippers   0.467

[22957 rows x 3 columns]

**PERSONAL FOULS**

In [108]:
PFs ='''
    SELECT "TEAM_ABBREVIATION"
    AS "nba_all_data.TEAM_ABBREVIATION" FROM nba_all_data GROUP BY "nba_all_data.TEAM_ABBREVIATION" HAVING "nba_all_data.PF" > 500;
        '''

PFs = pd.read_sql(PFs, engine)

PFs

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "nba_all_data.PF" does not exist
LINE 3: ... GROUP BY "nba_all_data.TEAM_ABBREVIATION" HAVING "nba_all_d...
                                                             ^

[SQL:
    SELECT "TEAM_ABBREVIATION"
    AS "nba_all_data.TEAM_ABBREVIATION" FROM nba_all_data GROUP BY "nba_all_data.TEAM_ABBREVIATION" HAVING "nba_all_data.PF" > 500;
        ]
(Background on this error at: http://sqlalche.me/e/13/f405)

In [121]:
# This one uses HAVING and GROUPBY. It shows that Boston Celtics was the only
# team with more than an average of 10 personal fouls per game.

PFs ='''

SELECT AVG("PF"), "TEAM_ABBREVIATION"
FROM nba_all_data
GROUP BY "TEAM_ABBREVIATION"
HAVING AVG("PF") > 10;
'''


PFs = pd.read_sql(PFs, engine)

PFs

         avg TEAM_ABBREVIATION
0  10.014839               BOS

In [130]:
## Sorted where first half score MAX was higher than 50.

Score ='''

SELECT MAX("PTS"), "TEAM_ABBREVIATION"
FROM nba_all_data
GROUP BY "TEAM_ABBREVIATION"
HAVING MAX("PTS") > 50;
'''


Score = pd.read_sql(Score, engine)

Score

    max TEAM_ABBREVIATION
0    84               DEN
1    81               CHI
2    75               IND
3    90               HOU
4    92               GSW
5    77               BOS
6    82               LAC
7    81               CLE
8    84               POR
9    83               ATL
10   67               NOK
11   80               NOP
12   85               DAL
13   87               SAC
14   88               MIL
15   77               WAS
16   75               NJN
17   70               NOH
18   81               BKN
19   71               CHH
20   81               LAL
21   79               TOR
22   77               SAS
23   79               OKC
24   77               CHA
25   81               MIN
26   81               PHX
27   86               MEM
28   82               NYK
29   81               ORL
30   73               SEA
31   83               PHI
32   82               MIA
33   81               UTA
34   76               DET

In [ ]:
c.execute('SELECT * FROM stocks WHERE symbol=?', t)

# Intro

In [28]:
query = '''
    SELECT * FROM nba_ht;
    '''
simpsons=pd.read_sql(query, engine)

In [29]:
simpsons

,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,2001-02,1610612765,DET,Detroit Pistons,20101181,2002-04-17T00:00:00,DET vs. MIL,W,24.0,25,46,0.543,8,12,0.667,6,7,0.857,9,18,27,16,8.0,5,1,2,9,0,64,20.0,1,1,1,1,1,71,327,283,8,119,129,1384,1662,529,259,403,172,168,1336,494,1673,707,903,80,50,50
1,2001-02,1610612749,MIL,Milwaukee Bucks,20101181,2002-04-17T00:00:00,MIL @ DET,L,24.0,19,40,0.475,2,6,0.333,4,8,0.500,5,11,16,8,7.0,4,2,1,11,0,44,-20.0,1,1190,1190,1190,1,987,1391,929,995,1160,1136,1903,1445,2170,1322,2044,2077,1963,986,856,1101,218,1555,80,1580,2320
2,2001-02,1610612758,SAC,Sacramento Kings,20101188,2002-04-17T00:00:00,SAC @ LAL,L,24.0,20,39,0.513,2,5,0.400,12,17,0.706,3,21,24,7,8.0,1,2,1,6,0,54,-2.0,1,1190,1190,1190,1,690,1636,515,995,1454,907,259,177,1514,1973,86,525,2144,1336,2146,1101,218,140,80,462,1318
3,2001-02,1610612752,NYK,New York Knicks,20101179,2002-04-17T00:00:00,NYK vs. NJN,L,24.0,18,45,0.400,3,14,0.214,4,4,1.000,9,17,26,9,8.0,2,1,0,11,1,43,4.0,1,1190,1190,1190,1,1280,450,1774,566,42,1781,1903,2153,1,259,602,271,1753,1336,1771,1673,1,1555,1,1723,790
4,2001-02,1610612737,ATL,Atlanta Hawks,20101176,2002-04-17T00:00:00,ATL @ BOS,L,24.0,13,43,0.302,0,3,0.000,13,16,0.813,10,17,27,8,8.0,8,2,4,4,0,39,-10.0,1,1190,1190,1190,1,2267,785,2341,2083,2001,2083,174,243,853,145,602,172,1963,1336,41,1101,1743,19,80,2076,1943
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92551,2020-21,1610612743,DEN,Denver Nuggets,22000019,2020-12-23T00:00:00,DEN vs. SAC,L,24.0,23,45,0.511,5,12,0.417,9,10,0.900,7,21,28,13,8.0,2,4,4,10,11,60,7.0,1,305,305,305,1,140,267,168,372,541,213,198,252,123,82,100,58,241,347,434,69,459,348,108,182,158
92552,2020-21,1610612751,BKN,Brooklyn Nets,22000001,2020-12-22T00:00:00,BKN vs. GSW,W,24.0,23,47,0.489,9,20,0.450,8,9,0.889,4,24,28,11,13.0,5,6,2,10,10,63,18.0,1,1,1,1,1,140,156,219,91,139,156,245,307,137,309,24,58,382,593,134,15,170,348,191,124,44
92553,2020-21,1610612747,LAL,Los Angeles Lakers,22000002,2020-12-22T00:00:00,LAL vs. LAC,L,24.0,17,40,0.425,5,17,0.294,15,20,0.750,3,21,24,10,11.0,3,0,0,12,17,54,-2.0,1,305,305,305,1,512,536,417,372,313,446,23,15,335,427,100,199,459,540,324,564,1,502,3,355,336
92554,2020-21,1610612744,GSW,Golden State Warriors,22000001,2020-12-22T00:00:00,GSW @ BKN,L,24.0,17,53,0.321,4,17,0.235,7,10,0.700,6,17,23,10,9.0,4,2,6,10,10,45,-18.0,1,305,305,305,1,512,14,592,466,313,522,300,252,416,136,311,249,459,420,223,267,584,348,191,541,562
92555,2020-21,1610612746,LAC,LA Clippers,22000002,2020-12-22T00:00:00,LAC @ LAL,W,24.0,21,45,0.467,7,21,0.333,7,9,0.778,3,18,21,12,12.0,7,0,0,17,12,56,2.0,1,1,1,1,1,260,267,285,211,94,352,300,307,298,427,254,366,322,573,33,564,1,605,68,293,250

In [ ]:
CREATE TABLE namename (column1)

In [31]:
query = '''BULK INSERT namename
   FROM '/Users/johnmetzger/Desktop/Coding/Projects/Project3/all_seasons_df.csv',
   WITH( FIRSTROW = 2,
         FIELDTERMINATOR = ',',
         ROWTERMINATOR = '\n')'''

ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "BULK"
LINE 1: BULK INSERT namename
        ^

[SQL: BULK INSERT namename
   FROM '/Users/johnmetzger/Desktop/Coding/Projects/Project3/all_seasons_df.csv',
   WITH( FIRSTROW = 2,
         FIELDTERMINATOR = ',',
         ROWTERMINATOR = '
')]
(Background on this error at: http://sqlalche.me/e/13/f405)