In [22]:
import pandas as pd

In [50]:
from nba_api.stats.endpoints import teamdashboardbygeneralsplits
# Anthony Davis
spurs = teamdashboardbygeneralsplits.TeamDashboardByGeneralSplits(team_id='1610612759')
a= spurs.get_data_frames()[1]

In [51]:
a

,GROUP_SET,GROUP_VALUE,TEAM_GAME_LOCATION,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,CFID,CFPARAMS
0,Location,Home,Home,10,5,5,0.500,480.0,428,917,0.467,102,276,0.370,155,208,0.745,102,359,461,251,118.0,75,45,61,178,185,1113,1.0,1,2,2,2,1,1,1,1,2,2,1,1,1,2,1,1,1,1,2,1,1,2,2,1,1,2,153,Home
1,Location,Road,Road,9,6,3,0.667,437.0,377,846,0.446,107,299,0.358,148,177,0.836,81,328,409,224,88.0,59,45,46,156,166,1009,25.0,2,1,1,1,2,2,2,2,1,1,2,2,2,1,2,2,2,2,1,2,1,1,1,2,2,1,153,Road

In [45]:
d.shape

(1, 56)

In [46]:
d

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,CFID,CFPARAMS
0,Overall,2020-21,19,11,8,0.579,917.0,805,1763,0.457,209,575,0.363,303,385,0.787,183,687,870,475,206.0,134,90,107,334,351,2122,26.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,151,2020-21

In [32]:
## This will allow me to see all the data columns

pd.set_option('display.max_columns', None)

In [34]:
a.head()

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,CFID,CFPARAMS
0,By Half,First Half,19,11,8,0.579,456.0,404,893,0.452,111,293,0.379,129,163,0.791,73,356,429,253,97.0,70,46,51,149,150,1048,23.0,1,1,2,2,1,1,1,2,1,1,2,2,2,2,2,1,2,1,2,1,1,2,2,2,2,1,148,First Half
1,By Half,Second Half,19,11,8,0.579,456.0,397,860,0.462,96,278,0.345,172,220,0.782,107,329,436,219,109.0,63,43,55,183,200,1062,0.0,1,1,2,2,1,2,2,1,2,2,3,1,1,3,1,2,1,2,3,2,2,3,3,1,1,3,148,Second Half
2,By Half,Overtime,1,1,0,1.000,5.0,4,10,0.400,2,4,0.500,2,2,1.000,3,2,5,3,0.0,1,1,1,2,1,12,3.0,3,3,1,1,3,3,3,3,3,3,1,3,3,1,3,3,3,3,1,3,3,1,1,3,3,2,148,Overtime